/** Gate 1 Sequence Scrub types — no WebCodecs / Playback fields. */

export type DeviceClass = "desktop" | "mobile";

export type TierId = "desktop-standard" | "desktop-lite" | "mobile";

export type RendererId = "sequence-scrub" | "poster";

export type RationalFps = { num: number; den: number; value: number };

export type SequenceTier = {
  id: TierId;
  device: DeviceClass;
  width: number;
  height: number;
  outputFps: number;
  sourceFps: number;
  frameCount: number;
  durationSec: number;
  totalBytes: number;
  avgFrameBytes: number;
  maxFrameBytes: number;
  contentHash: string;
  urlPattern: string;
  firstFrameUrl: string;
  lastFrameUrl: string;
  decodedCacheMax: number;
  estimatedDecodedCacheMb: number;
  prefetchAhead: number;
  prefetchBehind: number;
  maxActiveFetches: number;
};

export type MediaManifestV1 = {
  schemaVersion: number;
  mediaId: string;
  pipelineVersion: string;
  createdAt: string;
  posters: { desktop: string; mobile: string };
  policy: {
    decodedCacheMaxDefault: number;
    startupFramesMax: number;
    allowDesktopHigh: boolean;
  };
  tiers: SequenceTier[];
  sources: Record<string, unknown>;
};

export type EngineStats = {
  formFactor: DeviceClass;
  tierId: TierId | "poster" | null;
  renderer: RendererId;
  assetIntent: "sequence" | "poster";
  manifestVersion: number | null;
  sourceFps: number | null;
  outputFps: number | null;
  frameCount: number;
  targetFrame: number;
  displayedFrame: number | null;
  nearestCachedFrame: number | null;
  scrollDirection: -1 | 0 | 1;
  scrollVelocity: number;
  jumpActive: boolean;
  settled: boolean;
  decodedCacheCount: number;
  decodedCacheMax: number;
  cachedFrameIndexes: number[];
  prefetchAhead: number;
  prefetchBehind: number;
  activeFetches: number;
  activeDecodes: number;
  pendingTarget: number | null;
  framesRequested: number;
  framesDecoded: number;
  framesDrawn: number;
  framesEvicted: number;
  obsoleteTargetsSkipped: number;
  duplicateRequestsPrevented: number;
  decodeFailures: number;
  drawFailures: number;
  targetToDisplayMs: number | null;
  estimatedDecodedMemoryMb: number;
  canvasCssWidth: number;
  canvasCssHeight: number;
  dprRequested: number;
  dprApplied: number;
  fallbackReason: string | null;
  reducedMotion: boolean;
  saveData: boolean;
  targetGeneration: number;
  prefetchExpanded: boolean;
  invariantWarnings: string[];
  /** Progress pipeline debug (MediaView). */
  rawScrollProgress: number | null;
  frameProgress: number | null;
  mediaViewReceivedProgress: number | null;
  lastEngineProgress: number | null;
  /** Scheduler accounting (Gate 1 perf). */
  progressEvents: number;
  targetChanges: number;
  schedulerGenerations: number;
  ensureRequested: number;
  fetchQueued: number;
  fetchStarted: number;
  fetchCompleted: number;
  browserCacheHits: number;
  fetchAborted: number;
  fetchFailed: number;
  decodeStarted: number;
  decodeCompleted: number;
  decodeDiscardedStale: number;
  drawCalls: number;
  distinctFramesDrawn: number;
  evictions: number;
  dedupePrevented: number;
  /** Presentation truth */
  drawnFrame: number | null;
  selectedCacheFrame: number | null;
  actualBitmapFrame: number | null;
  displayedBitmapId: string | null;
  displayedSourceHashPrefix: string | null;
  requestedFrameIndex: number | null;
  requestedFrameUrl: string | null;
  responseUrl: string | null;
  responseBytes: number | null;
  responseHashPrefix: string | null;
  posterVisible: boolean;
  posterDisplay: string;
  posterOpacity: number;
  posterZIndex: number;
  canvasOpacity: number;
  canvasZIndex: number;
  hasPresentedFirstFrame: boolean;
  firstSuccessfulDrawFrame: number | null;
  bootstrapPhase: string;
  firstFramePresented: boolean;
  hasInteracted: boolean;
  prefetchPhase: string;
  idleAnchorWarmingActive: boolean;
  /** Tier policy (debug). */
  policyTier: TierId | "poster" | null;
  overrideTier: string | null;
  committedTier: TierId | "poster" | null;
  policyReason: string | null;
  committedReason: string | null;
  overrideAccepted: boolean;
  overrideIgnoreReason: string | null;
  viewportCssWidth: number;
  viewportCssHeight: number;
  viewportCssPixelArea: number;
  canvasBackingWidth: number;
  canvasBackingHeight: number;
  canvasBackingPixelArea: number;
  deviceMemoryGb: number | null;
  hardwareConcurrency: number | null;
  posterHintUrl: string | null;
  posterRuntimeUrl: string | null;
  posterUrlMatch: boolean | null;
  frame0HintUrl: string | null;
  frame0RuntimeUrl: string | null;
  frame0UrlMatch: boolean | null;
  tierCommittedAt: number | null;
  manifestRequestStart: number | null;
  manifestRequestEnd: number | null;
  posterRequestStart: number | null;
  posterRequestEnd: number | null;
  frame0RequestStart: number | null;
  frame0RequestEnd: number | null;
  frame0DecodeStart: number | null;
  frame0DecodeEnd: number | null;
  firstCanvasDrawAt: number | null;
  posterHiddenAt: number | null;
  firstInteractionAt: number | null;
  startupNetworkRequests: number;
  startupDecodes: number;
  startupDedupePrevented: number;
  targetLatencySamples: number[];
  coldRunwayEnabled: boolean;
  runwayTier: TierId | null;
  runwayPlannedRange: string;
  runwayRequestsStarted: number;
  runwayRequestsCompleted: number;
  runwaySkippedCached: number;
  runwayPausedOrAbandoned: number;
  runwayCompressedBytes: number;
  runwayByteBudget: number | null;
  runwayPriorityPreemptions: number;
  runwayStartedAt: number | null;
  runwayCompletedAt: number | null;
  runwayFailures: number;
  runwayDedupePrevented: number;
  runwayRunning: boolean;
  firstInteractionTargetLatencyMs: number | null;
  coldRunwayIgnoreReason: string | null;
  postReleaseLatencySamples: number[];
  readinessGateEnabled: boolean;
  readinessTier: TierId | null;
  readinessTotalFrames: number;
  readinessFramesCached: number;
  readinessFramesRequested: number;
  readinessFramesCompleted: number;
  readinessFramesFailed: number;
  readinessFramesInFlight: number;
  /** Live unique remaining: total − completed unique cached. */
  readinessFramesRemaining: number;
  readinessCompressedBytes: number;
  readinessEstimatedTierBytes: number;
  readinessPercentage: number;
  readinessGateStartAt: number | null;
  readinessFirstCanvasDrawAt: number | null;
  readinessFullReadyAt: number | null;
  readinessLoaderReleaseAt: number | null;
  readinessLoaderVisibleMs: number | null;
  readinessReleaseReason: string;
  readinessTimelineCoverage: number;
  readinessDedupePrevented: number;
  readinessRunning: boolean;
  readinessGateIgnoreReason: string | null;
  readinessTarget: number | null;
  readinessTargetIgnoreReason: string | null;
  readinessCompletedBytePercentage: number;
  readinessOpeningNeighbourhoodComplete: boolean;
  readinessThresholdReachedAt: number | null;
  readinessLoaderFadeStartAt: number | null;
  readinessFramesRemainingAtRelease: number | null;
  readinessBytesRemainingAtRelease: number | null;
  readinessBackgroundCompletionsAfterRelease: number;
  readinessPostReleasePriorityFetches: number;
  readinessPostReleaseMissingFrameCacheHits: number;
  readinessPredTierKnown: boolean;
  readinessPredFrame0Fetched: boolean;
  readinessPredFrame0Decoded: boolean;
  readinessPredFirstCanvasDraw: boolean;
  readinessPredNeighbourhood: boolean;
  readinessPredAnchors: boolean;
  readinessPredCompletedUnique: number;
  readinessPredCompletedFramePct: number;
  readinessPredCompletedBytePct: number;
  readinessPredCriticalFailures: number;
  readinessPredMinVisibleMet: boolean;
  readinessPredGateActive: boolean;
  readinessPredFadeRequested: boolean;
  readinessPredThresholdRequested: boolean;
  readinessPredTimeoutFired: boolean;
  readinessPredBlockingReason: string | null;
  scrollLockActive: boolean;
  scrollLockAtGateStart: number | null;
  scrollLockIntended: number | null;
  scrollLockMaxDeviation: number;
  scrollLockWheelBlocked: number;
  scrollLockTouchBlocked: number;
  scrollLockKeyboardBlocked: number;
  scrollLockAtRelease: number | null;
  scrollLockUnlockReason: string | null;
  scrollLockCleanupCompleted: boolean;
  scrollLockFreshTopEntry: boolean;
  scrollLockHistoryPreserve: boolean;
};

export type MediaEngineOptions = {
  canvas: HTMLCanvasElement;
  deviceClass: DeviceClass;
  mediaId?: string;
  manifestUrl?: string;
  poster?: string;
  reducedMotion?: boolean;
  /** Enables canvas watermark + blob hash prefixes. */
  debug?: boolean;
  /** Production readiness gate (default on via readReadinessGateFlag). */
  readinessGate?: boolean;
  onReady?: () => void;
  onFirstFrame?: () => void;
  onFatal?: (error: Error) => void;
  onStats?: (stats: EngineStats) => void;
  /** Progress 0–1 while readiness gate is warming compressed frames. */
  onReadinessProgress?: (pct: number) => void;
  /** Fired when readiness gate releases the loading overlay. */
  onReadinessRelease?: (reason: string) => void;
};
